import {
  Bell,
  Calendar,
  CheckSquare,
  Clock,
  CreditCard,
  Database,
  DollarSign,
  FileText,
  FolderKanban,
  GraduationCap,
  Heart,
  Home,
  ListTodo,
  Package,
  Search,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Trash2,
  Upload,
  UserCog,
  UserPlus,
  Users,
  Video,
} from "lucide-react";
import type { RegisteredModuleDefinition } from "../../core/tenant/registry-types";
import { AccessControl } from "../../modules/ong/app/pages/AccessControl";
import { Activities } from "../../modules/ong/app/pages/Activities";
import { AdmissionDocuments } from "../../modules/ong/app/pages/AdmissionDocuments";
import { AdmissionInterviews } from "../../modules/ong/app/pages/AdmissionInterviews";
import { AdmissionOnboarding } from "../../modules/ong/app/pages/AdmissionOnboarding";
import { AdmissionRequests } from "../../modules/ong/app/pages/AdmissionRequests";
import { Approvals } from "../../modules/ong/app/pages/Approvals";
import { Attendance } from "../../modules/ong/app/pages/Attendance";
import { AuditLog } from "../../modules/ong/app/pages/AuditLog";
import { Beneficiaries } from "../../modules/ong/app/pages/Beneficiaries";
import { Catalogs } from "../../modules/ong/app/pages/Catalogs";
import { Dashboard } from "../../modules/ong/app/pages/Dashboard";
import { Evidence } from "../../modules/ong/app/pages/Evidence";
import { Finance } from "../../modules/ong/app/pages/Finance";
import { GlobalSearch } from "../../modules/ong/app/pages/GlobalSearch";
import { Hours } from "../../modules/ong/app/pages/Hours";
import { HoursApproval } from "../../modules/ong/app/pages/HoursApproval";
import { IdCards } from "../../modules/ong/app/pages/IdCards";
import { Inventory } from "../../modules/ong/app/pages/Inventory";
import { MedicalRecords } from "../../modules/ong/app/pages/MedicalRecords";
import { NotificationHistory } from "../../modules/ong/app/pages/NotificationHistory";
import { NotificationTemplates } from "../../modules/ong/app/pages/NotificationTemplates";
import { Courses } from "../../modules/ong/app/pages/Courses";
import { ProjectActivities } from "../../modules/ong/app/pages/ProjectActivities";
import { ProjectAssignments } from "../../modules/ong/app/pages/ProjectAssignments";
import { Projects } from "../../modules/ong/app/pages/Projects";
import { Roles } from "../../modules/ong/app/pages/Roles";
import { Security } from "../../modules/ong/app/pages/Security";
import { SensitiveAccess } from "../../modules/ong/app/pages/SensitiveAccess";
import { SoftDelete } from "../../modules/ong/app/pages/SoftDelete";
import { SystemUsers } from "../../modules/ong/app/pages/SystemUsers";
import { Tasks } from "../../modules/ong/app/pages/Tasks";
import { Volunteers } from "../../modules/ong/app/pages/Volunteers";

const APP_BASE_PATH = "/app";
const ONG_BASE_PATH = `${APP_BASE_PATH}/ong`;
const SETTINGS_BASE_PATH = `${APP_BASE_PATH}/settings`;

const GROUPS = {
  home: { id: "home", label: "Home", icon: Home },
  proyectos: { id: "proyectos", label: "Proyectos", icon: FolderKanban },
  operacion: { id: "operacion", label: "Operacion", icon: Calendar },
  aprobaciones: { id: "aprobaciones", label: "Aprobaciones", icon: CheckSquare },
  personas: { id: "personas", label: "Personas", icon: Users },
  admision: { id: "admision", label: "Admision", icon: UserPlus },
  recursos: { id: "recursos", label: "Recursos", icon: Package },
  clinico: { id: "clinico", label: "Clinico", icon: ShieldAlert },
  notificaciones: { id: "notificaciones", label: "Notificaciones", icon: Bell },
  gobernanza: { id: "gobernanza", label: "Gobernanza", icon: Database },
  configuracion: { id: "configuracion", label: "Configuracion", icon: Settings },
  ace: { id: "ace", label: "Control de acceso", icon: ShieldCheck },
} as const;

export const ONG_MODULE_IDS = [
  "home",
  "projects",
  "operation",
  "approvals",
  "people",
  "admission",
  "resources.inventory",
  "resources.finance",
  "clinico",
  "notifications",
  "governance",
  "settings.users",
  "settings.roles",
  "settings.sessions",
  "settings.ace",
] as const;

export const ongModuleDefinitions: RegisteredModuleDefinition[] = [
  {
    moduleId: "home",
    industryIds: ["ong"],
    basePath: `${ONG_BASE_PATH}/home`,
    menuGroup: GROUPS.home,
    menuLabel: "Panel principal",
    icon: Home,
    requiredPermissions: ["home.read"],
    moduleKeys: ["home", "ong"],
    defaultRouteId: "home",
    routes: [
      {
        id: "home",
        label: "Panel principal",
        title: "Panel principal",
        path: `${ONG_BASE_PATH}/home`,
        legacyPath: "/admin",
        icon: Home,
        shortcutKeys: ["d"],
        moduleKeys: ["home", "ong"],
        anyPermissions: ["home.read"],
        element: <Dashboard />,
      },
      {
        id: "search",
        label: "Busqueda global",
        title: "Busqueda global",
        breadcrumb: "Home",
        path: `${ONG_BASE_PATH}/search`,
        legacyPath: "/admin/search",
        icon: Search,
        moduleKeys: ["home", "ong"],
        anyPermissions: ["home.read"],
        element: <GlobalSearch />,
      },
    ],
  },
  {
    moduleId: "projects",
    industryIds: ["ong"],
    basePath: `${ONG_BASE_PATH}/projects`,
    menuGroup: GROUPS.proyectos,
    menuLabel: "Proyectos",
    icon: FolderKanban,
    requiredPermissions: ["projects.read"],
    moduleKeys: ["projects", "ong"],
    defaultRouteId: "projects",
    routes: [
      {
        id: "projects",
        label: "Proyectos",
        title: "Proyectos",
        breadcrumb: "Proyectos",
        path: `${ONG_BASE_PATH}/projects`,
        legacyPath: "/admin/projects",
        icon: FolderKanban,
        shortcutKeys: ["p"],
        moduleKeys: ["projects", "ong"],
        anyPermissions: ["projects.read"],
        element: <Projects />,
      },
      {
        id: "tasks",
        label: "Tareas",
        title: "Tareas",
        breadcrumb: "Proyectos",
        path: `${ONG_BASE_PATH}/projects/tasks`,
        legacyPath: "/admin/tasks",
        icon: ListTodo,
        moduleKeys: ["projects", "ong"],
        anyPermissions: ["projects.read"],
        element: <Tasks />,
      },
      {
        id: "project-activities",
        label: "Actividades",
        title: "Actividades del proyecto",
        breadcrumb: "Proyectos",
        path: `${ONG_BASE_PATH}/projects/activities`,
        legacyPath: "/admin/project-activities",
        icon: Calendar,
        moduleKeys: ["projects", "ong"],
        anyPermissions: ["projects.read"],
        element: <ProjectActivities />,
      },
      {
        id: "project-assignments",
        label: "Asignaciones",
        title: "Asignaciones",
        breadcrumb: "Proyectos",
        path: `${ONG_BASE_PATH}/projects/assignments`,
        legacyPath: "/admin/project-assignments",
        icon: Users,
        moduleKeys: ["projects", "ong"],
        anyPermissions: ["projects.read"],
        element: <ProjectAssignments />,
      },
    ],
  },
  {
    moduleId: "operation",
    industryIds: ["ong"],
    basePath: `${ONG_BASE_PATH}/operation`,
    menuGroup: GROUPS.operacion,
    menuLabel: "Operacion",
    icon: Calendar,
    requiredPermissions: [
      "operation.activities.read",
      "operation.attendance.read",
      "attendance.scan",
      "operation.hours.read",
      "operation.evidence.read",
    ],
    moduleKeys: ["operation", "ong"],
    defaultRouteId: "operation-activities",
    routes: [
      {
        id: "operation-activities",
        label: "Actividades",
        title: "Actividades",
        breadcrumb: "Operacion",
        path: `${ONG_BASE_PATH}/operation/activities`,
        legacyPath: "/admin/activities",
        icon: Calendar,
        shortcutKeys: ["a"],
        moduleKeys: ["operation", "ong"],
        anyPermissions: ["operation.activities.read"],
        element: <Activities />,
      },
      {
        id: "operation-attendance",
        label: "Asistencias",
        title: "Asistencias",
        breadcrumb: "Operacion",
        path: `${ONG_BASE_PATH}/operation/attendance`,
        legacyPath: "/admin/attendance",
        icon: CheckSquare,
        moduleKeys: ["operation", "ong"],
        anyPermissions: ["operation.attendance.read", "attendance.scan"],
        element: <Attendance />,
      },
      {
        id: "operation-hours",
        label: "Horas",
        title: "Horas",
        breadcrumb: "Operacion",
        path: `${ONG_BASE_PATH}/operation/hours`,
        legacyPath: "/admin/hours",
        icon: Clock,
        shortcutKeys: ["h"],
        moduleKeys: ["operation", "ong"],
        anyPermissions: ["operation.hours.read"],
        element: <Hours />,
      },
      {
        id: "operation-evidence",
        label: "Evidencias",
        title: "Evidencias",
        breadcrumb: "Operacion",
        path: `${ONG_BASE_PATH}/operation/evidence`,
        legacyPath: "/admin/evidence",
        icon: Upload,
        moduleKeys: ["operation", "ong"],
        anyPermissions: ["operation.evidence.read"],
        element: <Evidence />,
      },
    ],
  },
  {
    moduleId: "approvals",
    industryIds: ["ong"],
    basePath: `${ONG_BASE_PATH}/approvals`,
    menuGroup: GROUPS.aprobaciones,
    menuLabel: "Aprobaciones",
    icon: CheckSquare,
    requiredPermissions: [
      "operation.hours.approve",
      "operation.evidence.approve",
      "admission.approve",
      "resources.finance.approve",
    ],
    moduleKeys: ["operation", "resources", "admission", "ong"],
    defaultRouteId: "approvals",
    routes: [
      {
        id: "approvals",
        label: "Bandeja",
        title: "Bandeja de aprobaciones",
        breadcrumb: "Aprobaciones",
        path: `${ONG_BASE_PATH}/approvals`,
        legacyPath: "/admin/approvals",
        icon: CheckSquare,
        moduleKeys: ["operation", "resources", "admission", "ong"],
        anyPermissions: [
          "operation.hours.approve",
          "operation.evidence.approve",
          "admission.approve",
          "resources.finance.approve",
        ],
        element: <Approvals />,
      },
      {
        id: "approvals-hours",
        label: "Aprobacion de horas",
        title: "Aprobacion de horas",
        breadcrumb: "Aprobaciones",
        path: `${ONG_BASE_PATH}/approvals/hours`,
        legacyPath: "/admin/approvals/hours",
        icon: Clock,
        shortcutKeys: ["h"],
        moduleKeys: ["operation", "ong"],
        anyPermissions: ["operation.hours.approve"],
        element: <HoursApproval />,
      },
    ],
  },
  {
    moduleId: "people",
    industryIds: ["ong"],
    basePath: `${ONG_BASE_PATH}/people`,
    menuGroup: GROUPS.personas,
    menuLabel: "Personas",
    icon: Users,
    requiredPermissions: [
      "volunteers.register",
      "volunteers.invite",
      "admission.read",
      "projects.read",
      "idcards.read",
      "home.read",
    ],
    moduleKeys: ["people", "ong"],
    defaultRouteId: "volunteers",
    routes: [
      {
        id: "volunteers",
        label: "Voluntarios",
        title: "Voluntarios",
        breadcrumb: "Personas",
        path: `${ONG_BASE_PATH}/people/volunteers`,
        legacyPath: "/admin/volunteers",
        icon: Users,
        shortcutKeys: ["v"],
        moduleKeys: ["people", "ong"],
        anyPermissions: ["volunteers.register", "volunteers.invite", "admission.read", "projects.read"],
        element: <Volunteers />,
      },
      {
        id: "id-cards",
        label: "Credenciales ID",
        title: "Credenciales ID",
        breadcrumb: "Personas",
        path: `${ONG_BASE_PATH}/people/id-cards`,
        legacyPath: "/admin/id-cards",
        icon: CreditCard,
        moduleKeys: ["idcards", "people", "ong"],
        anyPermissions: ["idcards.read"],
        element: <IdCards />,
      },
      {
        id: "beneficiaries",
        label: "Beneficiarios",
        title: "Beneficiarios",
        breadcrumb: "Personas",
        path: `${ONG_BASE_PATH}/people/beneficiaries`,
        legacyPath: "/admin/beneficiaries",
        icon: Heart,
        moduleKeys: ["people", "ong"],
        anyPermissions: ["admission.read", "projects.read", "home.read"],
        element: <Beneficiaries />,
      },
    ],
  },
  {
    moduleId: "admission",
    industryIds: ["ong"],
    basePath: `${ONG_BASE_PATH}/admission`,
    menuGroup: GROUPS.admision,
    menuLabel: "Admision",
    icon: UserPlus,
    requiredPermissions: ["admission.read"],
    moduleKeys: ["admission", "rrhh", "ong"],
    defaultRouteId: "admission-requests",
    routes: [
      {
        id: "admission-requests",
        label: "Solicitudes",
        title: "Solicitudes de admision",
        breadcrumb: "Admision",
        path: `${ONG_BASE_PATH}/admission/requests`,
        legacyPath: "/admin/admission/requests",
        icon: UserPlus,
        shortcutKeys: ["r"],
        moduleKeys: ["admission", "rrhh", "ong"],
        anyPermissions: ["admission.read"],
        element: <AdmissionRequests />,
      },
      {
        id: "admission-documents",
        label: "Documentos",
        title: "Documentos de admision",
        breadcrumb: "Admision",
        path: `${ONG_BASE_PATH}/admission/documents`,
        legacyPath: "/admin/admission/documents",
        icon: FileText,
        moduleKeys: ["admission", "rrhh", "ong"],
        anyPermissions: ["admission.read"],
        element: <AdmissionDocuments />,
      },
      {
        id: "admission-interviews",
        label: "Entrevistas",
        title: "Entrevistas",
        breadcrumb: "Admision",
        path: `${ONG_BASE_PATH}/admission/interviews`,
        legacyPath: "/admin/admission/interviews",
        icon: Video,
        moduleKeys: ["admission", "rrhh", "ong"],
        anyPermissions: ["admission.read"],
        element: <AdmissionInterviews />,
      },
      {
        id: "admission-onboarding",
        label: "Onboarding",
        title: "Onboarding",
        breadcrumb: "Admision",
        path: `${ONG_BASE_PATH}/admission/onboarding`,
        legacyPath: "/admin/admission/onboarding",
        icon: CheckSquare,
        moduleKeys: ["admission", "rrhh", "ong"],
        anyPermissions: ["admission.read"],
        element: <AdmissionOnboarding />,
      },
    ],
  },
  {
    moduleId: "resources.inventory",
    industryIds: ["ong"],
    basePath: `${ONG_BASE_PATH}/resources`,
    menuGroup: GROUPS.recursos,
    menuLabel: "Inventario",
    icon: Package,
    requiredPermissions: ["resources.inventory.read", "resources.finance.read"],
    moduleKeys: ["resources", "inventory", "ong"],
    defaultRouteId: "inventory",
    routes: [
      {
        id: "inventory",
        label: "Inventario",
        title: "Inventario",
        breadcrumb: "Recursos",
        path: `${ONG_BASE_PATH}/resources/inventory`,
        legacyPath: "/admin/inventory",
        icon: Package,
        moduleKeys: ["resources", "inventory", "ong"],
        anyPermissions: ["resources.inventory.read"],
        element: <Inventory />,
      },
      {
        id: "courses",
        label: "Cursos y certificados",
        title: "Cursos y certificados",
        breadcrumb: "Recursos",
        path: `${ONG_BASE_PATH}/resources/courses`,
        legacyPath: "/admin/courses",
        icon: GraduationCap,
        moduleKeys: ["resources", "ong"],
        anyPermissions: ["resources.inventory.read", "resources.finance.read"],
        element: <Courses />,
      },
    ],
  },
  {
    moduleId: "resources.finance",
    industryIds: ["ong"],
    basePath: `${ONG_BASE_PATH}/resources`,
    menuGroup: GROUPS.recursos,
    menuLabel: "Finanzas",
    icon: DollarSign,
    requiredPermissions: ["resources.finance.read"],
    moduleKeys: ["resources", "finanzas", "ong"],
    defaultRouteId: "finance",
    routes: [
      {
        id: "finance",
        label: "Finanzas",
        title: "Finanzas",
        breadcrumb: "Recursos",
        path: `${ONG_BASE_PATH}/resources/finance`,
        legacyPath: "/admin/finance",
        icon: DollarSign,
        moduleKeys: ["resources", "finanzas", "ong"],
        anyPermissions: ["resources.finance.read"],
        element: <Finance />,
      },
    ],
  },
  {
    moduleId: "clinico",
    industryIds: ["ong"],
    basePath: `${ONG_BASE_PATH}/clinico`,
    menuGroup: GROUPS.clinico,
    menuLabel: "Clinico",
    icon: ShieldAlert,
    requiredPermissions: ["clinico.volunteer_sensitive.read"],
    moduleKeys: ["clinico", "ong"],
    defaultRouteId: "medical-records",
    routes: [
      {
        id: "medical-records",
        label: "Ficha medica",
        title: "Ficha medica",
        breadcrumb: "Clinico",
        path: `${ONG_BASE_PATH}/clinico/medical-records`,
        legacyPath: "/admin/medical-records",
        icon: ShieldAlert,
        shortcutKeys: ["m"],
        moduleKeys: ["clinico", "ong"],
        anyPermissions: ["clinico.volunteer_sensitive.read"],
        element: <MedicalRecords />,
      },
    ],
  },
  {
    moduleId: "notifications",
    industryIds: ["ong"],
    basePath: `${ONG_BASE_PATH}/notifications`,
    menuGroup: GROUPS.notificaciones,
    menuLabel: "Notificaciones",
    icon: Bell,
    requiredPermissions: ["notifications.read"],
    moduleKeys: ["notifications", "comunicaciones", "ong"],
    defaultRouteId: "notifications-history",
    routes: [
      {
        id: "notifications-templates",
        label: "Plantillas",
        title: "Plantillas",
        breadcrumb: "Notificaciones",
        path: `${ONG_BASE_PATH}/notifications/templates`,
        legacyPath: "/admin/notifications/templates",
        icon: Bell,
        moduleKeys: ["notifications", "comunicaciones", "ong"],
        anyPermissions: ["notifications.read"],
        element: <NotificationTemplates />,
      },
      {
        id: "notifications-history",
        label: "Historial",
        title: "Historial",
        breadcrumb: "Notificaciones",
        path: `${ONG_BASE_PATH}/notifications/history`,
        legacyPath: "/admin/notifications/history",
        icon: FileText,
        moduleKeys: ["notifications", "comunicaciones", "ong"],
        anyPermissions: ["notifications.read"],
        element: <NotificationHistory />,
      },
    ],
  },
  {
    moduleId: "governance",
    industryIds: ["ong"],
    basePath: `${ONG_BASE_PATH}/governance`,
    menuGroup: GROUPS.gobernanza,
    menuLabel: "Gobernanza",
    icon: Database,
    requiredPermissions: [
      "governance.catalogs.read",
      "governance.audit.read",
      "governance.sensitive.read",
      "governance.retention.read",
    ],
    moduleKeys: ["governance", "auditoria", "ong"],
    defaultRouteId: "catalogs",
    routes: [
      {
        id: "catalogs",
        label: "Catalogos",
        title: "Catalogos",
        breadcrumb: "Gobernanza",
        path: `${ONG_BASE_PATH}/governance/catalogs`,
        legacyPath: "/admin/catalogs",
        icon: Database,
        moduleKeys: ["governance", "auditoria", "ong"],
        anyPermissions: ["governance.catalogs.read"],
        element: <Catalogs />,
      },
      {
        id: "audit-log",
        label: "Auditoria",
        title: "Auditoria",
        breadcrumb: "Gobernanza",
        path: `${ONG_BASE_PATH}/governance/audit-log`,
        legacyPath: "/admin/audit-log",
        icon: FileText,
        moduleKeys: ["governance", "auditoria", "ong"],
        anyPermissions: ["governance.audit.read"],
        element: <AuditLog />,
      },
      {
        id: "sensitive-access",
        label: "Accesos sensibles",
        title: "Accesos sensibles",
        breadcrumb: "Gobernanza",
        path: `${ONG_BASE_PATH}/governance/sensitive-access`,
        legacyPath: "/admin/sensitive-access",
        icon: ShieldAlert,
        moduleKeys: ["governance", "auditoria", "clinico", "ong"],
        anyPermissions: ["governance.sensitive.read"],
        element: <SensitiveAccess />,
      },
      {
        id: "soft-delete",
        label: "Retencion",
        title: "Retencion y borrado",
        breadcrumb: "Gobernanza",
        path: `${ONG_BASE_PATH}/governance/soft-delete`,
        legacyPath: "/admin/soft-delete",
        icon: Trash2,
        moduleKeys: ["governance", "auditoria", "ong"],
        anyPermissions: ["governance.retention.read", "governance.audit.read"],
        element: <SoftDelete />,
      },
    ],
  },
  {
    moduleId: "settings.users",
    industryIds: ["ong"],
    basePath: SETTINGS_BASE_PATH,
    menuGroup: GROUPS.configuracion,
    menuLabel: "Usuarios del sistema",
    icon: UserCog,
    requiredPermissions: ["settings.users.read"],
    moduleKeys: ["settings", "ong"],
    defaultRouteId: "system-users",
    routes: [
      {
        id: "system-users",
        label: "Usuarios del sistema",
        title: "Usuarios del sistema",
        breadcrumb: "Configuracion",
        path: `${SETTINGS_BASE_PATH}/users`,
        legacyPath: "/admin/system-users",
        aliases: [`${ONG_BASE_PATH}/settings/users`],
        icon: UserCog,
        moduleKeys: ["settings", "ong"],
        anyPermissions: ["settings.users.read"],
        element: <SystemUsers />,
      },
    ],
  },
  {
    moduleId: "settings.roles",
    industryIds: ["ong"],
    basePath: SETTINGS_BASE_PATH,
    menuGroup: GROUPS.configuracion,
    menuLabel: "Roles y permisos",
    icon: Shield,
    requiredPermissions: ["settings.roles.read"],
    moduleKeys: ["settings", "ong"],
    defaultRouteId: "roles",
    routes: [
      {
        id: "roles",
        label: "Roles y permisos",
        title: "Roles y permisos",
        breadcrumb: "Configuracion",
        path: `${SETTINGS_BASE_PATH}/roles`,
        legacyPath: "/admin/roles",
        aliases: [`${ONG_BASE_PATH}/settings/roles`],
        icon: Shield,
        moduleKeys: ["settings", "ong"],
        anyPermissions: ["settings.roles.read"],
        element: <Roles />,
      },
    ],
  },
  {
    moduleId: "settings.sessions",
    industryIds: ["ong"],
    basePath: SETTINGS_BASE_PATH,
    menuGroup: GROUPS.configuracion,
    menuLabel: "Seguridad de sesion",
    icon: Settings,
    requiredPermissions: ["settings.sessions.read"],
    moduleKeys: ["settings", "ong"],
    defaultRouteId: "security",
    routes: [
      {
        id: "security",
        label: "Seguridad de sesion",
        title: "Seguridad de sesion",
        breadcrumb: "Configuracion",
        path: `${SETTINGS_BASE_PATH}/sessions`,
        legacyPath: "/admin/security",
        aliases: [`${ONG_BASE_PATH}/settings/security`],
        icon: Settings,
        moduleKeys: ["settings", "ong"],
        anyPermissions: ["settings.sessions.read"],
        element: <Security />,
      },
    ],
  },
  {
    moduleId: "settings.ace",
    industryIds: ["ong"],
    basePath: SETTINGS_BASE_PATH,
    menuGroup: GROUPS.ace,
    menuLabel: "Control de acceso",
    icon: ShieldCheck,
    requiredPermissions: ["ace.access_links.read", "ace.memberships.read"],
    moduleKeys: ["ace", "settings", "ong"],
    defaultRouteId: "access-control",
    routes: [
      {
        id: "access-control",
        label: "Control de acceso",
        title: "Control de acceso (ACE)",
        breadcrumb: "Configuracion",
        path: `${SETTINGS_BASE_PATH}/access-control`,
        legacyPath: "/admin/access-control",
        aliases: [`${ONG_BASE_PATH}/settings/access-control`],
        icon: ShieldCheck,
        moduleKeys: ["ace", "settings", "ong"],
        anyPermissions: ["ace.access_links.read", "ace.memberships.read"],
        element: <AccessControl />,
      },
    ],
  },
];
