/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

type MaybeString = string | undefined | null;

const LEGACY_PROJECT_ID = 'qafvnjoqvdtnrdvlnwco';
const LEGACY_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhZnZuam9xdmR0bnJkdmxud2NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNzYzOTUsImV4cCI6MjA4NTY1MjM5NX0.xcbA7Ve7MaELXbsIt49m25ulDyFiHmk8cpXXkzhS3jw';

const PLACEHOLDER_VALUES = new Set([
  '',
  'hola',
  'your-project-id',
  'your-anon-key',
  'changeme',
  'undefined',
  'null',
]);

function normalize(value: MaybeString): string {
  return (value || '').trim();
}

function isPlaceholder(value: MaybeString): boolean {
  const normalized = normalize(value).toLowerCase();
  return PLACEHOLDER_VALUES.has(normalized);
}

function projectIdFromUrl(urlValue: MaybeString): string {
  const value = normalize(urlValue);
  if (!value) return '';

  try {
    const hostname = new URL(value).hostname;
    const suffix = '.supabase.co';
    if (!hostname.endsWith(suffix)) return '';
    return hostname.slice(0, hostname.length - suffix.length);
  } catch {
    return '';
  }
}

const envProjectId = normalize(import.meta.env.VITE_SUPABASE_PROJECT_ID);
const envUrl = normalize(import.meta.env.VITE_SUPABASE_URL);
const envAnonKey = normalize(import.meta.env.VITE_SUPABASE_ANON_KEY);

const resolvedProjectId = envProjectId || projectIdFromUrl(envUrl) || LEGACY_PROJECT_ID;
const resolvedAnonKey = envAnonKey || LEGACY_ANON_KEY;

export const projectId = isPlaceholder(resolvedProjectId) ? '' : resolvedProjectId;
export const publicAnonKey = isPlaceholder(resolvedAnonKey) ? '' : resolvedAnonKey;
export const supabaseConfigured = Boolean(projectId && publicAnonKey);

if (import.meta.env.DEV && !supabaseConfigured) {
  console.error(
    '[Supabase config] Faltan variables de configuracion. Define VITE_SUPABASE_PROJECT_ID o VITE_SUPABASE_URL y VITE_SUPABASE_ANON_KEY.',
  );
}
